version: '3'

services:
  nextcloud:
    image: nextcloud:29.0.5
    container_name: nextcloud
    restart: unless-stopped
    links:
      - mariadb
    volumes:
      - ${PATH_NEXTCLOUD_CONFIG}:/var/www/html
      - ${PATH_NEXTCLOUD}:/var/www/html/data
#    ports:
#      - 8081:80
    environment:
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - OVERWRITEHOST=${OVERWRITEHOST}
      - OVERWRITEPROTOCOL=https

    hostname: ${HOST_NAME}
  mariadb:
    image: mariadb:11.5.2
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ${PATH_MARIADB}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASS}
      - MYSQL_PASSWORD=${ENV_MYSQL_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  cloudflared:
    image: cloudflare/cloudflared:2024.8.3-amd64
    container_name: cloudflared-use-nextcloud
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
  
  nginx:
      image: nginx:1.27.1
      container_name: nginx-use-nextcloud
      restart: unless-stopped
      ports:
        - "8081:443"
      volumes:
        - ./Nginxdefault.conf:/etc/nginx/conf.d/default.conf
        - ./keydata:/etc/nginx/keydata