version: '3'

volumes:
  nextcloud:
  mariadb:

services:
  nextcloud:
    image: nextcloud:25.0.2
    container_name: nextcloud
    restart: unless-stopped
    links:
      - mariadb
    volumes:
      - nextcloud:/var/www/html
      - ${PATH_NEXTCLOUD}:/var/www/html/data
    ports:
      - 8081:80
    environment:
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - OVERWRITEPROTOCOL=https
  mariadb:
    image: mariadb:10.10.2
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ${PATH_MARIADB}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASS}
      - MYSQL_PASSWORD=${ENV_MYSQL_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  cloudflared:
      image: cloudflare/cloudflared:2022.12.1-amd64
      container_name: cloudflared-use-nextcloud
      restart: unless-stopped
      command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
