version: '3'

volumes:
  nextcloud:
  mariadb:

services:
  nextcloud:
    image: nextcloud:25.0.2
    container_name: nextcloud
    restart: unless-stopped
    links:
      - mariadb
    volumes:
      - nextcloud:/var/www/html
    ports:
      - 8081:80
  
  mariadb:
    image: mariadb:10.9.4
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASS}
      - MYSQL_PASSWORD=${ENV_MYSQL_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
